---
sidebar: sidebar
permalink: rn/whats_new.html
keywords: whats new, enhancements, new features
summary: NetApp regularly updates the Astra Control REST API to bring you new features, enhancements, and bug fixes.
---

= What's new with the Astra Control REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp regularly updates the Astra Control REST API to bring you new features, enhancements, and bug fixes.

== 10 August 2022 (22.08)

This release includes an expansion and update of the REST API as well as enhanced security and administrative features.

=== New and enhanced Astra resources

Three new resources types have been added: *Certificate*, *Group*, and *AppMirror*. In addition, the versions of several existing resources have been updated.

=== LDAP authentication

You can optionally configure Astra Control Center to integrate with an LDAP server to authenticate selected Astra users. See link:../workflows_infra/ldap_prepare.html[LDAP configuration] for more information.

=== Enhanced execution hook

Support for execution hooks was added with the Astra Control 21.12 release. In addition to the existing pre-snapshot and post-snapshot execution hooks, you can now configure the following types of execution hooks with the 22.08 release:

* Pre-backup
* Post-backup
* Post-restore

Astra Control now also allows same script to be used for multiple execution hooks.

=== Application replication using SnapMirror

You can now replicate data and application changes among clusters using NetApp SnapMirror technology. This enhancement can be used to improve your business continuity and recovery capabilities.

.Related information

* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html[Astra Control Center: What's new^]

* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html[Astra Control Service: What's new^]

== 26 April 2022 (22.04)

This release includes an expansion and update of the REST API as well as enhanced security and administrative features.

=== New and enhanced Astra resources

Two new resources types have been added: *Package* and *Upgrade*. In addition, the versions of several existing resources have been upgraded.

=== Enhanced RBAC with namespace granularity

When binding a role to an associated user, you can limit the namespaces the user has access to. See the *Role Binding API* reference and link:../additional/rbac.html[RBAC security] for more information.

=== Bucket removal

You can remove a bucket when it is no longer needed or is not functioning properly.

=== Support for Cloud Volumes ONTAP

Cloud Volumes ONTAP is now supported as a storage backend.

=== Additional product enhancements

There are several additional enhancements to the two Astra Control product implementations, including:

* Generic ingress for Astra Control Center
* Private cluster in AKS
* Support for Kubernetes 1.22
* Support for VMware Tanzu portfolio

See the *What's new* page at the Astra Control Center and Astra Control Service documentation sites.

.Related information

* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html[Astra Control Center: What's new^]

* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html[Astra Control Service: What's new^]

== 14 December 2021 (21.12)

This release includes an expansion of the REST API along with a change to the documentation structure to better support the evolution of Astra Control through the future release updates.

=== Separate Astra Automation documentation for each release of Astra Control

Every release of Astra Control includes a distinct REST API that has been enhanced and tailored to the features of the specific release. The documentation for each release of the Astra Control REST API is now available at its own dedicated web site along with the associated GitHub content repository. The main doc site https://docs.netapp.com/us-en/astra-automation/[Astra Control Automation^] always contains the documentation for the most current release. See link:../aa-earlier-versions.html[Earlier versions of Astra Control Automation documentation] for information about prior releases.

=== Expansion of the REST resource types

The number of REST resource types has continued to expand with an emphasis on execution hooks and storage backends. The new resources include: account, execution hook, hook source, execution hook override, cluster node, managed storage backend, namespace, storage device, and storage node. See link:../endpoints/resources.html[Resources] for more information.

=== NetApp Astra Control Python SDK

NetApp Astra Control Python SDK is an open source package that makes it easier to develop automation code for your Astra Control environment. At the core is the Astra SDK which includes a set of classes to abstract the complexity of the REST API calls. There is also a toolkit script to execute specific administrative tasks by wrapping and abstracting the Python classes. See link:../python/astra_toolkits.html[NetApp Astra Control Python SDK] for more information.

== 5 August 2021 (21.08)

This release includes the introduction of a new Astra deployment model and a major expansion of the REST API.

=== Astra Control Center deployment model

In addition to the existing Astra Control Service offering provided as a public cloud service, this release also includes the Astra Control Center on-premises deployment model. You can install Astra Control Center at your site to manage your local Kubernetes environment. The two Astra Control deployment models share the same REST API, with minor differences noted as needed in the documentation.

=== Expansion of the REST resource types

The number of resources accessible through the Astra Control REST API has greatly expanded, with many of the new resources providing a foundation for the on-premises Astra Control Center offering. The new resources include: ASUP, entitlement, feature, license, setting, subscription, bucket, cloud, cluster, managed cluster, storage backend, and storage class. See link:../endpoints/resources.html[Resources] for more information.

=== Additional endpoints supporting an Astra deployment

In addition to the expanded REST resources, there are several other new API endpoints available to support an Astra Control deployment.

OpenAPI support::
The OpenAPI endpoints provide access to the current OpenAPI JSON document and other related resources.

OpenMetrics support::
The OpenMetrics endpoints provide access to account metrics through the OpenMetrics resource.

== 15 April 2021 (21.04)

This release includes the following new features and enhancements.

=== Introduction of the REST API

The Astra Control REST API is available for use with the Astra Control Service offering. It has been created based on REST technologies and current best practices. The API provides a foundation for the automation of your Astra deployments and includes the following features and benefits.

Resources::
There are fourteen REST resource types available.

API token access::
Access to the REST API is provided through an API access token which you can generate at the Astra web user interface. The API token provides secure access to the API.

Support for collections::
There is a rich set of query parameters which can be used to access the resources collections. Some of the supported operations include filtering, sorting, and pagination.
